default_dir = ["./prompts"]
cache_dir = "./.pm-cache"

[file_system]
extensions = [".md", ".txt"]
ignore_patterns = [".DS_Store"]
max_file_size_kb = 128

[fuzzy_search]
max_results = 20

[ui]
truncate_length = 120
